spring:
    application:
        name: @artifactId@
        version: @project.version@
    data:
        mongodb:
            uri: mongodb://localhost:27017/db_siscom
    output:
        ansi:
            enabled: ALWAYS
